version: '3.8'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
#    restart: always
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - /node_modules/

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
#    networks:
#      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8081:80"
#    networks:
#      - postgres

#networks:
#  postgres:
#    driver: bridge

volumes:
  postgres:
  pgadmin:
